namespace: nexushr

backend:
  image: ghcr.io/ybhukya48-naik/nexushr-backend:latest
  replicas: 3

frontend:
  image: ghcr.io/ybhukya48-naik/nexushr-frontend:latest
  replicas: 2

ingress:
  host: nexushr.local
