ALTER TABLE employees
ADD COLUMN lifecycle_status VARCHAR(50);

UPDATE employees
SET lifecycle_status = CASE
    WHEN active = TRUE THEN 'ACTIVE'
    ELSE 'OFFBOARDED'
END;

ALTER TABLE employees
ALTER COLUMN lifecycle_status SET NOT NULL;

CREATE TABLE employee_lifecycle_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    from_status VARCHAR(50),
    to_status VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL,
    comments VARCHAR(1000),
    changed_by VARCHAR(255),
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_lifecycle_history_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE TABLE employee_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    document_type VARCHAR(100) NOT NULL,
    document_url VARCHAR(1000),
    uploaded_by VARCHAR(255),
    uploaded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_employee_document_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id)
);
