CREATE TABLE performance_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    target_score INTEGER NOT NULL,
    achieved_score INTEGER NOT NULL,
    due_date DATE NOT NULL,
    completed BOOLEAN NOT NULL,
    CONSTRAINT fk_performance_goal_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE TABLE performance_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comments VARCHAR(2000) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_performance_feedback_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_performance_feedback_reviewer
        FOREIGN KEY (reviewer_id) REFERENCES employees(id)
);

CREATE INDEX idx_performance_goal_employee
    ON performance_goals(employee_id);

CREATE INDEX idx_performance_feedback_employee
    ON performance_feedback(employee_id);

CREATE INDEX idx_performance_feedback_reviewer
    ON performance_feedback(reviewer_id);
